services:
  nvscan:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nvscan

    ports:
      - "5000:5000"

    environment:
      NVSCAN_SECRET_KEY: "change-this-secret-key"

    volumes:
      - ./nvscan.db:/app/nvscan.db

    restart: unless-stopped
